# Generated by Django 4.2.14 on 2024-07-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proj", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("bookid", models.AutoField(primary_key=True, serialize=False)),
                ("bookname", models.CharField(max_length=100)),
            ],
        ),
    ]
