# Generated by Django 4.2.14 on 2024-07-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proj", "0002_book"),
    ]

    operations = [
        migrations.DeleteModel(name="Book",),
    ]
